config/routes.rb
Pamir::Application.routes.draw do

  devise_for :users, :path_prefix => 'd'

  resources :users do
    resource :spouse
    resources :children
    resources :parents
    resources :roles
  end

  resource :users_import, only: [:create]
  resource :users_exports, only: [:show]

  resources :roles do
    resources :users
  end

  resources :parenthoods

  get 'search/new' => 'search#new'
  get 'search' => 'search#show'

  root :to => "users#index"
end

app/models/search.rb
class Search

  include ActiveModel::Model

  attr_accessor :first_name, :email, :last_name, :middle_name, :university, :role, :language, :spouse, :children,
                :gender, :nationality

  def initialize(params = {})
    @first_name = params[:first_name]
    @last_name = params[:last_name]
    @middle_name = params[:middle_name]
    @email = params[:email]
    @university = params[:university]
    @role = params[:role]
    @language = params[:language]
    @spouse = params[:spouse]
    @children = params[:children]
    @gender = params[:gender]
    @nationality = params[:nationality]  
  end

  def perform
    scope = UsersIndex::User.query(match_all: { } )
    fields = {languages: language, roles: role, spouse: spouse, email: email, first_name: first_name, university: university,
              middle_name: middle_name, last_name: last_name, children: children, gender: gender, nationality: nationality}
    fields.each{ |k, v| scope = scope.query(match: { k => v } ) unless v.blank? }
    scope
  end

  def self.model_name
    ActiveModel::Name.new(self, nil, "Search")
  end

  def persisted?
    true
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def new
    @search = Search.new
  end

  def show
    @search = Search.new(params[:search])
    @users = @search.perform
  end
end

app/views/search/new.html.erb
<div class="index-container">
  <div class="index-header">Пользователи</div>
  <div class="content-container clearfix">
    <div class="index-sidebar col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li><%= link_to "ПОЛЬЗОВАТЕЛИ", users_path %></li>
        <li><%= link_to "ОТЧЕТЫ" %></li>
        <li><%= link_to "ДОБАВИТЬ", new_user_path %></li>
        <li><%= link_to "НАЙТИ", search_new_path %></li>        
      </ul>    
    </div>
    <div class="index-content col-md-9">
      <div class="search-wipper">
        <div class="new-contact">
          <h4 class="about-contact">Поиск</h4>
        </div>
        <%= form_for @search, builder: ::SearchFormBuilder, method: :get do |f| %>
          <div class="form group col-md-12 search-form">
            <%= f.last_name %>
            <%= f.first_name %>
            <%= f.middle_name %>
            <%= f.email %>
            <%= f.university %>    
            <%= f.role %>
            <%= f.language %>
            <div class="form group col-md-12">
            <strong class="col-md-3 text-right">наличие супруга</strong>
              <%= f.spouse  %>
            </div>
            <div class="form group col-md-12">
            <strong class="col-md-3 text-right">наличие детей</strong>
              <%= f.children  %>
            </div>
            <div class="form group col-md-12">
            <strong class="col-md-3 text-right">пол</strong>
              <%= f.gender  %> 
            </div>
            <div class="form-group col-md-12">
              <%= f.submit 'сохранить', class: "btn btn-primary col-md-3 text-right" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="index-footer">
  </div>
</div>

app/views/search/show.html.erb
<div class="index-container">
  <div class="index-header">Пользователи</div>
  <div class="content-container clearfix">
    <div class="index-sidebar col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li><%= link_to "ПОЛЬЗОВАТЕЛИ", users_path %></li>
        <li><%= link_to "ОТЧЕТЫ" %></li>
        <li><%= link_to "ДОБАВИТЬ", new_user_path %></li>
        <li><%= link_to "НАЙТИ", search_new_path %></li>        
      </ul>    
    </div>
    <div class="index-content col-md-9">
      <div class="search-wipper">
        <div class="new-contact">
          <h4 class="about-contact">найденные пользователи</h4>
        </div>
        <ul>
          <% @users.each do |index_user| %>
            <li>
              <h3>
                <%= link_to "#{index_user.first_name} #{index_user.last_name}", user_path(index_user.id) %>
              </h3>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="index-footer">
  </div>
</div>