config/routes.rb
Pamir::Application.routes.draw do

  devise_for :users, :path_prefix => 'd'

  resources :users do
    resource :spouse
    resources :children
    resources :parents
    resources :roles
  end

  resource :users_import, only: [:create]
  resource :users_exports, only: [:show]

  resources :roles do
    resources :users
  end

  resources :parenthoods

  get 'search/new' => 'search#new'
  get 'search' => 'search#show'

  root :to => "users#index"
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_xlsx

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  validates :email, uniqueness: true

  has_and_belongs_to_many :roles

  has_many :parenthoods
  has_many :children, through: :parenthoods

  has_many :marriages
  has_many :spouses, through: :marriages

  has_many :proficiencies
  has_many :languages, through: :proficiencies

  as_enum :gender, female: 1, male: 0
  as_enum :education, primary: 0, middle: 1, high: 2, student: 3
  as_enum :grade, none: 0, bachelor: 1, specialist: 2, master: 3, dr: 4
  as_enum :income, less_500: 0, less_1000: 1, more_1000: 2
  as_enum :state_of_living, temporarily: 0, permanently: 1
  as_enum :state_of_occupation, free: 0, busy: 1
  as_enum :marital_status, single: 0, married: 1, divorced: 2
  as_enum :state_of_separation, together: 0, apart: 1

  accepts_nested_attributes_for :proficiencies, allow_destroy: true
  accepts_nested_attributes_for :children, allow_destroy: true
  accepts_nested_attributes_for :spouses, allow_destroy: true

  after_create :set_default_role

  paginates_per 15

  def password_required?
    false
  end

  def email_required?
    false
  end

  def fullname
    [first_name, last_name].join(" ")
  end

  def add_role(name)
    unless self.roles.find_by_name(name)
      self.roles << Role.find_by_name(name)
    end
  end

  def delete_role(name)
    roles.delete(Role.find_by_name(name))
  end

  def has_any_role?(*args)
    !(self.roles.map(&:name)&args).empty?
  end

  def has_any_of_roles?
    !Role.where(id: self.role_ids).empty?
  end

  def set_default_role
    self.add_role("user")
  end

  def self.admins
    self.joins(:roles).where(roles: {name: "admin"})
  end

  def set_language_proficiency(language_id, level)
    proficiency = proficiencies.where(language_id: language_id, user_id: self.id).first_or_initialize
    proficiency.update_attribute(:level, level)
  end

  def proficiency_for(language)
    Proficiency.find_by(user: self, language: language)
  end

  def parents
    parent_ids = Parenthood.where(child_id: id).pluck(:user_id)
    User.find(parent_ids)
  end

  def add_spouse(user)
    self.spouse = user
    user.spouse = self
  end

  def add_child(user)
    self.children << user
  end

  def add_parent(user)
    user.children << self
  end
end

app/controllers/users_controller.rb
require 'axlsx'

class UsersController < ApplicationController

  before_action :find_user, only: [:destroy, :show, :edit, :update, :new_parent, :create_parent]

  def index
    @users = User.order(:last_name).page params[:page]
    respond_to do |format|
      format.html
      format.json { render json: @users}
    end
  end

  def show
  end

  def new
    @user = User.new
    @user.languages.new
    @user.proficiencies.new
    @user.children.new
    @user.spouses.new
  end

  def create
    @user = User.new(user_params)
    authorize @user
    if @user.save
      flash[:success] = "Профайл успешно создан."
      redirect_to @user
    else
      flash[:error] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def update
    authorize @user
    if @user.update(user_params)
      params[:user][:language_ids].each do |a, b|
        @user.set_language_proficiency(b[:lang_id], b[:level])
      end
      if spouse = User.where(id: params[:select_spouse]).first
        @user.add_spouse(spouse)
      end
      if parent = User.where(id: params[:select_parent]).first
        @user.add_parent(parent)
      end
      if child = User.where(id: params[:select_child]).first
        @user.add_child(child)
      end
      flash[:success] = "Профайл был изменен."
      redirect_to @user
    else
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  def edit
    @user_options = User.all.collect { |u| [u.fullname, u.id] }
    @user.languages.new
    @user.proficiencies.new
    @user.children.new
    @user.spouses.new
  end

  def destroy
    authorize @user
    @user.delete
    respond_to do |format|
      format.html { redirect_to users_path }
      format.js
    end
  end

  private

  def user_params
    params[:user][:role_ids] ||= []
    params[:user][:language_ids] ||= []
    params.require(:user).permit(:email, :middle_name, :first_name, :last_name, :phone, :gender_cd, :grade,
                                 :university, :language_id, :profession, :year_of_grace, :other_lang,
                                 :birthday, :education, :user_helps_gamoat, :bp_country, :bp_address, :bp_gamoat,
                                 :lp_country, :lp_address, :lp_district_metro, :year_of_marriage, :year_of_graduation, :current_occupation,
                                 :income, :nationality, :state_of_living, :state_of_occupation, :state_of_separation, :marital_status,
                                 :other_nationality, :russian, :tajik, {role_ids: []}, {language_ids: []},
                                 languages_attributes: [:id, :name, :_destroy], proficiencies_attributes: [:language_id,
                                 :level, :_destroy], children_attributes: [:id, :email, :first_name, :last_name,
                                 :middle_name, :gender_cd, :current_occupation, :state_of_separation, :birthday,
                                 :_destroy], spouses_attributes: [:id, :email, :first_name, :last_name, :middle_name,
                                 :gender_cd, :current_occupation, :year_of_marriage, :state_of_separation, :birthday,
                                 :_destroy])
  end

  def find_user
    @user = User.find(params[:id]||params[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def show_static_field(label, data)
    html = <<-HTML
    <div class="form-group">
      <label class="col-sm-4 control-label">#{label}</label>
      <div class="col-sm-8">
        <p class="form-control-static">#{data}</p>
      </div>
    </div>
    HTML
    html.html_safe
  end
end

app/views/users/_add_relatives.html.erb
<%= fields_for object, as: as, url: url do |f| %>
  <div class="form-group">
  <% if object.parents.count < 2 %>
    <%= link_to "добавить родителя", new_user_parent_path(object), class: "btn btn-info btn-xs active" %>
    или
    <%= select_tag "e2", options_for_select(@user_options), name: "select_parent", include_blank: true %>
  <% end %>    
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="new-contact">
  <h4 class="about-contact">O контакте</h4>
</div>
<div class="forma">
  <%= nested_form_for object, as: as, url: url do |f| %>
    <div class="form-group form-inline col-md-12">
      <%= f.label :last_name, "Фамилия", class: "col-md-3 text-right"%>
      <%= f.text_field :last_name, class: "form-control col-md-9 xt-input" %>
    </div>
    <div class="form-group form-inline col-md-12">
      <%= f.label :first_name, "Имя", class: "col-md-3 text-right" %>
      <%= f.text_field :first_name, class: "form-control col-md-9 xt-input" %>
    </div>
    <div class="form-group form-inline col-md-12">
      <%= f.label :middle_name, "Отчество", class: "col-md-3 text-right" %>
      <%= f.text_field :middle_name, class: "form-control col-md-9 xt-input" %>
    </div>
    <div class="form-group form-inline col-md-12">
      <div class="col-md-3 text-right"><b>Пол</b></div>
      <% User.genders_for_select.each do |e| %>
        <div class="radio col-md-1">
          <%= radio_button_tag("user[gender_cd]", User.genders[e.last]) %>
          <%= label_tag("user[gender_cd]", e.first) %>
        </div>
      <% end %>
    </div>
    <div class="form-group form-inline col-md-12">
      <%= f.label :birthday, "дата рождения", class: "col-md-3 text-right" %>
      <%= f.text_field :birthday, class: "datepicker form-control col-md-9 tr-input" %>
    </div>
    <div class="form-group form-inline col-md-12">
      <%= f.label :email, "Еmail", class: "col-md-3 text-right" %>
      <%= f.text_field :email, class: "form-control col-md-9 tr-input" %>
    </div>
    <div class="form-group form-inline col-md-12">
      <%= f.label :phone, "Телефон", class: "col-md-3 text-right" %>
      <%= f.text_field :phone, class: "form-control col-md-9 tr-input" %>
    </div>
    <div class="form-group form-inline col-md-12">
      <div class="col-md-3 text-right"><b>Место рождения</b></div>
      <div class="form-group col-md-3 tripple-field">
        <%= f.text_field :bp_country, {class: "form-control tr-input", placeholder: "Страна"} %>
      </div>
      <div class="form-group col-md-3 tripple-field">
        <%= f.text_field :bp_address, {class: "form-control", placeholder: "Город/поселок"} %>
      </div>
      <div class="form-group col-md-3 tripple-field">
        <%= f.text_field :bp_gamoat, {class: "form-control", placeholder: "Джамоат"} %>
      </div>
    </div>
    <div class="form-group form-inline col-md-12">
      <div class="col-md-3 text-right"><b>Место проживания</b></div>
      <div class="form-group col-md-3 tripple-field">
        <%= f.text_field :lp_country, {class: "form-control tr-input", placeholder: "Страна"} %>
      </div>
      <div class="form-group col-md-3 tripple-field">
        <%= f.text_field :lp_address, {class: "form-control", placeholder: "Город/поселок"} %>
      </div>
      <div class="form-group col-md-3 tripple-field">
        <%= f.text_field :lp_district_metro, {class: "form-control", placeholder: "Район/метро"} %>
      </div>
    </div>
    <div class="form-group form-inline col-md-12">
        <%= f.label :state_of_living, "постоянно/временно", class: "col-md-3 text-right" %>
        <%= f.select :state_of_living, User.state_of_livings.keys, {}, class: "form-control col-md-9 tr-input" %>
    </div>
    <div class="form-group form-inline col-md-12">
      <div class="col-md-3 text-right"><b>Национальность</b></div>
        <div class="checkbox col-md-3 tripple-field">
          <%= f.check_box(:russian) %>
          <%= label_tag(:russian, "РФ") %>
          <%= f.check_box(:tajik) %>
          <%= label_tag(:tajik, "РТ") %>
        </div>
      <div class="form-group">
        <%= f.text_field :other_nationality, {class: "form-control col-md-3", placeholder: "другое"} %>
      </div>
    </div>
    <div class="form-group form-inline col-md-12">
      <div class="col-md-3 text-right"><b>Семейное положение</b></div>
      <% User.marital_statuses_for_select.each do |e| %>
        <div class="radio col-md-2">
          <% options = { checked: true} if e.last == f.object.marital_status %>
          <%= radio_button_tag("user[marital_status]", e.last, options) %>
          <%= label_tag(:marital_status_label, e.first) %>
        </div>
      <% end %>
    </div>
    <div class="form-group form-inline col-md-12">
      <div class="col-md-3 text-right"><b>Жена/муж</b></div>
      <div class="col-md-9 spouse-border">
      <table id="spouses">
        <%= f.fields_for :spouses do |s| %>
        <div class="nested-form col-md-12">
          <%= s.label :last_name, "Фамилия", class: "col-md-2 text-right"%>
          <%= s.text_field :last_name, class: "form-control col-md-10 nested-input" %>
        </div>
        <div class="nested-form col-md-12">
          <%= s.label :first_name, "Имя", class: "col-md-2 text-right" %>
          <%= s.text_field :first_name, class: "form-control col-md-10 nested-input" %>
        </div>
        <div class="nested-form col-md-12">
          <%= s.label :middle_name, "Отчество", class: "col-md-2 text-right" %>
          <%= s.text_field :middle_name, class: "form-control col-md-10 nested-input" %>
        </div>
        <div class="nested-form col-md-12">
          <%= s.label :email, "Еmail", class: "col-md-2 text-right" %>
          <%= s.text_field :email, class: "form-control col-md-5 bdate" %>
        </div>
        <div class="nested-form col-md-12">
          <%= s.label :birthday, "дата рождения", class: "col-md-2 text-right" %>
          <%= s.text_field :birthday, class: "datepicker form-control col-md-5 bdate" %>
          <%= s.label :year_of_marriage, "в браке с", class: "col-md-2 text-s" %>
          <%= s.text_field :year_of_marriage, class: "datepicker form-control col-md-3 " %>
        </div>
        <div class="nested-form col-md-12">
          <div class="col-md-2 text-right"><b>пол</b></div>
          <% User.genders_for_select.each do |e| %>
            <div class="radio col-md-2">
              <%= s.radio_button("gender_cd", User.genders[e.last]) %>
              <%= s.label("gender_cd", e.first) %>
            </div>
          <% end %>
          <div class="col-md-2 text-s"><b>проживает</b></div>
          <% User.state_of_separations_for_select.each do |e| %>
            <div class="radio col-md-2">
              <%= s.radio_button("state_of_separation_cd", User.state_of_separations[e.last]) %>
              <%= s.label("state_of_separation_cd", e.first) %>
            </div>
          <% end %>
        </div>
        <%= s.link_to_remove "убрать форму" %>
        <% end %>
      </table>
      <p>
        <%= f.link_to_add "добавить супруга", :spouses, :data => { :target => "#spouses" }, class: "btn btn-default col-md-4 col-md-offset-4 add-button" %>
      </p>
      </div>
    </div>
    <div class="form-group form-inline col-md-12">
      <div class="col-md-3 text-right"><b>Дети</b></div>
      <div class="col-md-9 spouse-border">
      <table id="children">
        <%= f.fields_for :children do |ch| %>
        <div class="nested-form col-md-12">
          <%= ch.label :last_name, "Фамилия", class: "col-md-2 text-right"%>
          <%= ch.text_field :last_name, class: "form-control col-md-10 nested-input" %>
        </div>
        <div class="nested-form col-md-12">
          <%= ch.label :first_name, "Имя", class: "col-md-2 text-right" %>
          <%= ch.text_field :first_name, class: "form-control col-md-10 nested-input" %>
        </div>
        <div class="nested-form col-md-12">
          <%= ch.label :middle_name, "Отчество", class: "col-md-2 text-right" %>
          <%= ch.text_field :middle_name, class: "form-control col-md-10 nested-input" %>
        </div>
        <div class="nested-form col-md-12">
          <%= ch.label :email, "Еmail", class: "col-md-2 text-right" %>
          <%= ch.text_field :email, class: "form-control col-md-5 bdate" %>
        </div>
        <div class="nested-form col-md-12">
          <%= ch.label :birthday, "дата рождения", class: "col-md-2 text-right" %>
          <%= ch.text_field :birthday, class: "datepicker form-control col-md-5 bdate" %>
        </div>
        <div class="nested-form col-md-12">
          <div class="col-md-2 text-right"><b>пол</b></div>
          <% User.genders_for_select.each do |e| %>
            <div class="radio col-md-2">
              <%= ch.radio_button("gender_cd", User.genders[e.last]) %>
              <%= ch.label("gender_cd", e.first) %>
            </div>
          <% end %>
          <div class="col-md-2 text-s"><b>проживает</b></div>
          <% User.state_of_separations_for_select.each do |e| %>
            <div class="radio col-md-2">
              <%= ch.radio_button("state_of_separation_cd", User.state_of_separations[e.last]) %>
              <%= ch.label("state_of_separation_cd", e.first) %>
            </div>
          <% end %>
        </div>
        <div class="nested-form col-md-12 ">
          <%= ch.label :current_occupation, "школа/дет.сад", class: "col-md-2 text-right"%>
          <%= ch.text_field :current_occupation, class: "form-control col-md-10 nested-input" %>
        </div>
        <%= ch.link_to_remove "убрать форму" %>
        <% end %>
      </table>
      <p>
        <%= f.link_to_add "добавить ребенка", :children, :data => { :target => "#children" }, class: "btn btn-default col-md-4 col-md-offset-4 add-button" %>
      </p>
      </div>
    </div>
    <div class="form-group form-inline col-md-12">
      <div class="col-md-3 text-right"><b>Образование</b></div>
      <div class="form-group col-md-3 tripple-field">
        <%= f.select :education, User.educations.keys, {}, class: "form-control tr-input" %>
      </div>
      <div class="form-group col-md-3 tripple-field">
        <%= f.label :grade, "степень" %>
        <%= f.select :grade, User.grades.keys, {}, class: "form-control" %>
      </div>
      <div class="form-group col-md-3 tripple-field">
        <%= f.label :year_of_graduation, "год" %>
        <%= f.text_field :year_of_graduation, class: "datepicker form-control" %>
      </div>
    </div>
    <div class="form-group form-inline col-md-12">
      <%= f.label :university, "оконченное учебное заведение", class: "col-md-3 text-right" %>
        <%= f.text_field :university, class: "form-control col-md-9 xt-input" %>
    </div>
    <div class="form-group form-inline col-md-12">
        <%= f.label :profession, "специальность", class: "col-md-3 text-right" %>
        <%= f.text_field :profession, class: "form-control col-md-9 xt-input" %>
    </div>
    <div class="form-group form-inline col-md-12">
      <div class="col-md-3 text-right"><b>иностранный язык</b></div>
      <div class="form-group col-md-4 tripple-field lang ">
      <table id="proficiencies">
        <%= f.fields_for :proficiencies do |l| %>
          <%= l.select :language_id, Language.all.map{|l| [l.name, l.id] }, class: "form-control col-md-2 nested-fields" %>
          <%= l.select :level, [['basic',1],['intermidiate',2],['advanced',3]], class: "form-control col-md-2 nested-fields" %>
          <%= l.link_to_remove "убрать поле", class: "nested-fields" %>
        <% end %>
      </table>
      </div>
      <div class="form-group col-md-3 tripple-field lang ">
        <p><%= f.link_to_add "добавить язык", :proficiencies, :data => { :target => "#proficiencies" } %></p>
      </div>
    </div>
    <div class="form-group form-inline col-md-12">
      <%= f.label :other_lang, "другие иностранные языки", class: "col-md-3 text-right" %>
      <%= f.text_field :other_lang, class: "form-control col-md-9 xt-input" %>
    </div>
    <div class="form-group form-inline col-md-12">
      <div class="col-md-3 text-right"><b>текущее место работы/учебы с указанием должности</b></div>
      <div class="form-group col-md-4 tripple-field">
        <%= f.text_field :current_occupation, class: "form-control occupation-input" %>
      </div>
      <div class="form-group col-md-2 tripple-field">
        <%= f.label :income, "доход" %>
        <%= f.select :income, User.incomes.keys, {}, class: "form-control" %>
      </div>
      <div class="form-group col-md-2 tripple-field occupied">
        <%= f.label :state_of_occupation, "занятость" %>
        <%= f.select :state_of_occupation, User.state_of_occupations.keys, {}, class: "form-control occupied-input" %>
      </div>
    </div>
    <div class="form-group form-inline col-md-12">
      <%= f.label :user_helps_gamoat, "В какой сфере может быть полезен джамоату", class: "col-md-3 text-right" %>
      <%= f.text_field :user_helps_gamoat, class: "form-control col-md-9 xt-input" %>
    </div>
    <div class="form-group form-inline col-md-12">
      <div class="col-md-3 text-right"><b>права доступа</b></div>
      <% Role.all.each do |role| %>
        <div class="checkbox col-md-2">
          <%= check_box_tag "user[role_ids][]", role.id, f.object.roles.include?(role), id: "user_role_ids_#{role.id}" %>
          <%= role.name %>
        </div>
      <% end %>
    </div>
    <div class="form-group col-md-12">
      <%= f.submit 'сохранить', class: "btn btn-primary col-md-3 text-right" %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<div class="contact"><%= "Профиль пользователя ID #{@user.id}" %></div>
<div class="forma">
  <form class="form-horizontal" role="form">
    <%=  show_static_field('Имя', @user.first_name)%>
    <%=  show_static_field('Фамилия', @user.last_name)%>
    <%=  show_static_field('Отчество', @user.middle_name)%>
    <%=  show_static_field('дата рождения', @user.birthday)%>
    <%=  show_static_field('пол', @user.gender)%>
    <%=  show_static_field('email', @user.email)%>
    <%=  show_static_field('номер телефона', @user.phone)%>
    <p>место рождения</p>
    <%=  show_static_field('страна', @user.bp_country)%>
    <%=  show_static_field('адрес', @user.bp_address)%>
    <%=  show_static_field('джамоат', @user.bp_gamoat)%>
    <p>место проживания</p>
    <%=  show_static_field('как долго', @user.state_of_living)%>
    <%=  show_static_field('страна', @user.lp_country)%>
    <%=  show_static_field('адрес', @user.lp_address)%>
    <%=  show_static_field('район/ст.метро', @user.lp_district_metro)%>
    <%=  show_static_field('русский', @user.russian)%>
    <%=  show_static_field('таджик', @user.tajik)%>
    <%=  show_static_field('другая национальность', @user.other_nationality)%>
    <%=  show_static_field('образование', @user.education)%>
    <%=  show_static_field('степень', @user.grade)%>
    <%=  show_static_field('оконченное учебное заведение', @user.university)%>
    <%=  show_static_field('специальность по диплому', @user.profession)%>
    <%=  show_static_field('дата получения диплома', @user.year_of_graduation)%>
    <%=  show_static_field('работает/учится', @user.state_of_occupation)%>
    <%=  show_static_field('текущее место работы/учебы', @user.current_occupation)%>
    <%=  show_static_field('доход', @user.income)%>
    <%=  show_static_field('семейное положение', @user.marital_status)%>
    <%=  show_static_field('какой сфере может быть полезен джамоату', @user.user_helps_gamoat)%>
    <%=  show_static_field('дата вступления в брак', @user.year_of_marriage)%>
    <%=  show_static_field('с супругом проживает отдельно или совместно', @user.state_of_separation)%>
    <% unless @user.languages.empty? %>
      <% @user.languages.each do |language| %>
        <%=  show_static_field('язык', language.name)%>
        <%=  show_static_field('уровень владения', @user.proficiency_for(language).level)%>
      <% end %>
    <% end %>
    <%=  show_static_field('другие иностранные языки', @user.other_lang)%>
  </form>
  <h5> Супруг/Супруга </h5>
    <% unless @user.spouses.empty? %>
      <% @user.spouses.each do |spouse| %>
      <div>
        <%= link_to spouse.fullname, user_path(spouse), class: 'user' %> |
        <%= link_to "удалить", user_spouse_path(@user, spouse), method: :delete %>
      </div>
    <% end %>
    <% end %>
  <h5> Родители </h5>
    <% unless @user.parents.empty? %>
      <% @user.parents.each do |parent| %>
        <div>
          <%= link_to parent.fullname, user_path(parent), class: 'user' %> |
          <%= link_to "удалить", user_parent_path(@user, parent), method: :delete %>
        </div>
      <% end %>
    <% end %>
  <h5> Дети </h5>
    <% unless @user.children.empty? %>
      <% @user.children.each do |child| %>
        <div>
          <%= link_to child.fullname, user_path(child), class: 'user' %> |
          <%= link_to "удалить", user_child_path(@user, child), method: :delete %>
        </div>
      <% end %>
    <% end %>
</div>
<div class="contact">Дополнительно</div>
<% unless @user.roles.empty? %>
  <h5> права доступа </h5>
  <% @user.roles.each do |role| %>
    <div>
      <%= role.name %>
    </div>
  <% end %>
<% end %>
<div class="contact-user">
  <%= mail_to @user.email, "Связаться с пользователем" %>
</div>

app/views/users/destroy.js.erb
$("#table_row_<%= @user.id %>").fadeOut();

app/views/users/edit.html.erb
<div class="index-container">
  <div class="index-header">Пользователи</div>
  <div class="content-container clearfix">
    <div class="index-sidebar col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li><%= link_to "ПОЛЬЗОВАТЕЛИ", users_path %></li>
        <li><%= link_to "ОТЧЕТЫ" %></li>
        <li><%= link_to "ДОБАВИТЬ", new_user_path %></li>
        <li><%= link_to "НАЙТИ", search_new_path %></li>        
      </ul>    
    </div>
    <div class="index-content col-md-9">
      <%= render "users/form", object: @user, as: :user, url: user_path %>
    </div>
  </div>
  <div class="show-footer text-right">
      <%= link_to "вернуться в профайл пользователя", @user, class: "btn btn-info btn-xs active" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="index-container">
  <div class="index-header">Пользователи</div>
  <div class="content-container clearfix">
    <div class="index-sidebar col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li><%= link_to "ПОЛЬЗОВАТЕЛИ", users_path %></li>
        <li><%= link_to "ОТЧЕТЫ" %></li>
        <li><%= link_to "ДОБАВИТЬ", new_user_path %></li>
        <li><%= link_to "НАЙТИ", search_new_path %></li>        
      </ul>    
    </div>
    <div class="index-content col-md-9">
      <table class="table table-striped">
        <tr>
          <td>
            ФИО
          </td>
          <td>
            пол
          </td>
          <td>
            дата рождения
          </td>
          <td>
            дата регистрации
          </td>
          <td>
            оператор
          </td>
          <td>
            прочее
          </td>   
        </tr>
        <% @users.each do |user| %>
          <tr id="table_row_<%= user.id %>">
            <td>
              <%= link_to("#{user.first_name} #{user.middle_name} #{user.last_name}", user, {:class => "user"}) %>
            </td>
            <td>
              <%= user.gender %>
            </td>
            <td>
              <%= user.birthday %>
            </td>
            <td>
            </td>   
            <td>
              <% user.roles.each do |role| %>
               <%= "#{role.name}" %><br>
              <% end %>
            </td>
            <td>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="index-footer">
    <%= paginate @users, theme: 'twitter-bootstrap-3' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="index-container">
  <div class="index-header">Пользователи</div>
  <div class="content-container clearfix">
    <div class="index-sidebar col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li><%= link_to "ПОЛЬЗОВАТЕЛИ", users_path %></li>
        <li><%= link_to "ОТЧЕТЫ" %></li>
        <li><%= link_to "ДОБАВИТЬ", new_user_path %></li>
        <li><%= link_to "НАЙТИ", search_new_path %></li>        
      </ul>    
    </div>
    <div class="index-content col-md-9">
      <p><%= render "users/form", object: @user, as: :user, url: users_path %></p>
    </div>
  </div>
  <div class="index-footer">
    <div class="export">
      ВЫГРУЗИТЬ ПОЛЬЗОВАТЕЛЕЙ В ФОРМАТЕ:
      <%= link_to 'Excelx', users_exports_path(format: "xlsx") %> |
      <%= link_to "CSV", users_exports_path(format: "csv") %> |
      <%= link_to "Excel", users_exports_path(format: "xls") %>
    </div>
    <div class="import">
      ДОБАВИТЬ ПОЛЬЗОВАТЕЛЕЙ:
      <%= form_tag users_import_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Сохранить", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="index-container">
  <div class="index-header">Пользователи</div>
  <div class="content-container clearfix">
    <div class="index-sidebar col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li><%= link_to "ПОЛЬЗОВАТЕЛИ", users_path %></li>
        <li><%= link_to "ОТЧЕТЫ" %></li>
        <li><%= link_to "ДОБАВИТЬ", new_user_path %></li>
        <li><%= link_to "НАЙТИ", search_new_path %></li>        
      </ul>    
    </div>
    <div class="index-content col-md-9 show-form">
      <p><%= render "users/user", object: @user, as: :user, url: user_path %></p>
    </div>
  </div>
  <div class="show-footer text-right">
    <%= link_to "редактировать", edit_user_path(@user), class: "btn btn-info btn-xs active" %>
    <%= link_to "удалить", user_path(@user), method: :delete, confirm: "You sure?", class: "btn btn-danger btn-xs active" %>
  </div>
</div>